export const LANGUAGE_VERSIONS = {
  python: "3.10.0",
  javascript: "18.15.0",
  java: "15.0.2",
  csharp: "6.12.0",
  ruby: "3.2.1",
  php: "8.2.3",
  swift: "5.8.0",
  go: "1.20.4",
  typescript: "5.0.3",
  c: "17.0",
  cpp: "20.0",
  kotlin: "1.8.10",
  rust: "1.69.0",
  dart: "2.19.6",
};

export const CODE_SNIPPETS = {
  python: `\ndef greet(name):\n\tprint("Hello, " + name + "!")\n\ngreet("Alex")\n`,
  javascript: `\nfunction greet(name) {\n\tconsole.log("Hello, " + name + "!");\n}\n\ngreet("Alex");\n`,
  java: `\npublic class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello World");\n\t}\n}\n`,
  csharp: 'using System;\n\nnamespace HelloWorld\n{\n\tclass Hello { \n\t\tstatic void Main(string[] args) {\n\t\t\tConsole.WriteLine("Hello World in C#");\n\t\t}\n\t}\n}\n',
  ruby: `\ndef greet(name)\n\tputs "Hello, #{name}!"\nend\n\ngreet("Alex")\n`,
  php: `<?php\n\n$name = 'Alex';\necho $name;\n?>`,
  swift: `\nfunc greet(name: String) {\n\tprint("Hello, \\(name)!")\n}\n\ngreet(name: "Alex")\n`,
  go: `\npackage main\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello, Alex!")\n}\n`,
  typescript: `\ntype Params = {\n\tname: string;\n}\n\nfunction greet(data: Params) {\n\tconsole.log("Hello, " + data.name + "!");\n}\n\ngreet({ name: "Alex" });\n`,
  c: `\n#include <stdio.h>\n\nint main() {\n\tprintf("Hello, Alex!\\n");\n\treturn 0;\n}\n`,
  cpp: `\n#include <iostream>\n\nint main() {\n\tstd::cout << "Hello, Alex!" << std::endl;\n\treturn 0;\n}\n`,
  kotlin: `\nfun main() {\n\tprintln("Hello, Alex!")\n}\n`,
  rust: `\nfn main() {\n\tprintln!("Hello, Alex!");\n}\n`,
  dart: `\nvoid main() {\n\tprint('Hello, Alex!');\n}\n`,
};
